
on: 
  issues: 
    types: 
    - opened
    - edited
    - deleted
    - transferred
    - pinned
    - unpinned
    - closed
    - reopened
    - assigned
    - unassigned
    - labeled
    - unlabeled
    - locked
    - unlocked
    - milestoned
    - demilestoned
jobs: 
  RunGitPub: 
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps: 
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Use GitPub Action
        uses: StartAutomating/GitPub@main
        id: GitPub
        with: 
          TargetBranch: edits-$([DateTime]::Now.ToString("o").Replace(":","-"))
          PublishParameters: |
            {
                "Get-GitPubIssue": {
                    "UserName": "StartAutomating",
                    "Repository": "GitPub",
                    "IssueState": "All"
                },
                "Publish-GitPubJekyll": {
                    "OutputPath": "docs/_posts"
                }
            }

